### ISSUE TITLE
Move PR template to .github folder

### ISSUE THREAD

**Issue by yvesgurcan** [yvesgurcan/web-midi-player#144]
## Problem

*Describe the problem related to this feature request.*

When non-functional updates are brought to the library, it's not relevant to have the checklist about making sure that the library builds, that tests pass, and so forth.

## Solution

*What solution do you suggest to solve this problem?*

Create a simpler template asking the user to describe the changes in the PR without the checklist.

**Comment by globefire** [comment]
@yvesgurcan PR template as in a HTML template or just a .md template?

**Comment by yvesgurcan** [comment]
@globefire Absolutely! There is a Markdown template for PRs here: https://github.com/yvesgurcan/web-midi-player/blob/master/PULL_REQUEST_TEMPLATE. Unfortunately, it looks like it is not possible or desirable to have multiple PR templates in GitHub. Therefore, I suggest that you simply move the existing template inside the `.github` dorectory. What do you think?

**Comment by theOpetunde** [comment]
Hello @yvesgurcan , I am a first-timer contributor and would love to solve this issue. But, I am a little confused as to what I should do here. Or has the issue already been solved?

**Comment by globefire** [comment]
hey, @theOpetunde you are welcome to solve the issue. I am looking for a solution. If you find it feel free to make the PR.

**Comment by globefire** [comment]
> @globefire Absolutely! There is a Markdown template for PRs here: https://github.com/yvesgurcan/web-midi-player/blob/master/PULL_REQUEST_TEMPLATE. Unfortunately, it looks like it is not possible or desirable to have multiple PR templates in GitHub. Therefore, I suggest that you simply move the existing template inside the `.github` directory. What do you think?

Hey @yvesgurcan, sure sounds good. Just to make it clear, you are suggesting that [https://github.com/yvesgurcan/web-midi-player/blob/master/PULL_REQUEST_TEMPLATE](https://github.com/yvesgurcan/web-midi-player/blob/master/PULL_REQUEST_TEMPLATE)
 this template should be pushed to the `.github` folder?

**Comment by yvesgurcan** [comment]
Hey @globefire and @theOpetunde,
Yes, since it is not possible to have multiple PR templates in GitHub, we can change the issue to simply moving `./PULL_REQUEST_TEMPLATE` to `.github/PULL_REQUEST_TEMPLATE`. Feel free to fork the project and open a pull request to do that! I will update the title of the issue.

**Comment by theOpetunde** [comment]
@yvesgurcan Thank you for the explanation

**Comment by globefire** [comment]
@theOpetunde since this is your first time, you make a PR.
@yvesgurcan is there any other issue I can work on?

**Comment by theOpetunde** [comment]
Thank you @globefire. You're very kind

@yvesgurcan I have made a PR to solve the issue. Please check if I am correct and your feedback will be appreciated.

**Comment by yvesgurcan** [comment]
Great job @theOpetunde! I've approved and merged your PR.

@globefire, there's plenty to do! If you want to keep working on good first issues, you can always look here: https://github.com/yvesgurcan/web-midi-player/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22. More specifically, you are more than welcome to open a PR for #47 or #38. If you're feeling more adventurous and want to write some code in React, there's also #12 . Let me know if you need help running the example on your machine.

**Comment by globefire** [comment]
Thanks @yvesgurcan, I would love to work on the react issue. I'll try to run the example if required I will ping you.
