### ISSUE TITLE
Fix link to workflow files in README

### ISSUE THREAD

**Issue by yvesgurcan** [yvesgurcan/web-midi-player#145]
## Problem

*Describe the problem related to this feature request.*

In the README, the link that is supposed to browse to the workflow folder redirects to `here` instead.

## Solution

*What solution do you suggest to solve this problem?*

The target of the link and the text that describes it were inverted. Simply switch them back. This is an issue related to Markdown syntax.

**Comment by rehasantiago** [comment]
I have solved this issue in #148. Kindly check my PR

**Comment by yvesgurcan** [comment]
Great work! If you would like to grab another issue, this one is also beginner friendly: #46
