### ISSUE TITLE
Bug template: Incentivize to share screenshots

### ISSUE THREAD

**Issue by yvesgurcan** [yvesgurcan/web-midi-player#46]
In the bug report Markdown template (https://github.com/yvesgurcan/web-midi-player/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), ask reporters to share screenshots in the "Example" section of the template. Section should be renamed "Example/Screenshots" and add a few words about adding screenshots to the report.

**Comment by hkbiet** [comment]
Hi , i am a first time user/contributor to this and am trying to work on this issue by making the changes as asked. But the pull request shows some errors doing some automated checks ... can you please help on this as to what am i doing wrong though i followed whatever was mentioned/documented ?
https://github.com/yvesgurcan/web-midi-player/pull/150 
#150

**Comment by yvesgurcan** [comment]
Hey Hemant,
Thank you so much for your first contribution! 🎉 Don't worry about the automated checks not working. I think there are some hiccups with the scripts. I can bypass them and merge your PR. I have suggested a few changes in #150. Can you look into them?
